#!/usr/bin/env python3
"""Generate the OpenPLC **v3** thermal-plant gateway program and I/O map.

Same job as ``tools/generate_openplc_gateway.py`` (data exchange + logic, never
control), but for OpenPLC Runtime v3, whose Modbus master image is fixed by the
runtime instead of chosen in the editor.

From ``webserver/core/modbus_master.cpp`` (v3):

* every polled device appends to one packed buffer per table, in the order the
  slave devices are configured;
* those buffers are copied to ``%IX100.0+``, ``%QX100.0+``, ``%IW100+`` and
  ``%QW100+``;
* each buffer holds at most ``MAX_MB_IO`` (400) entries.

With 8 devices that budget allows 49 input words each (392 of 400), so v3 reads
the full FC4 contract image but has **no** room for the FC3 holding readback,
and one coil block of 8 bits per device (the generator's breaker coils at
offsets 9/10 are v4-only - the generator synchronises itself anyway).

``webserver/core/modbus.cpp`` shows the northbound server exposes the same
``%IW``/``%QW``/``%IX``/``%QX`` image, so SCADA addresses are derived directly
from the local IEC addresses; ``northbound-map.csv`` lists them.
"""
from __future__ import annotations

import argparse
import csv
import io
import sys
from pathlib import Path
from typing import Sequence

from tools.generate_openplc_gateway import (  # reuse the single source of truth
    COMMAND_HOLDING_START,
    COMMAND_HOLDING_LENGTH,
    CONTAINER_HOSTS,
    DEVICE_ORDER,
    ECHO_STALE_TICKS,
    HOST_PORTS,
    OVERSPEED_RAW_RPM,
    PULSE_SCANS,
    RESET_KEY,
    Register,
    TASK_INTERVAL_MS,
    WATCHDOG_SCANS,
    alias,
    contract_index,
    load_contract,
    slug,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MAP = REPO_ROOT / "docs" / "register-map.csv"
DEFAULT_OUTPUT = REPO_ROOT / "integrations" / "openplc" / "thermal-plant-v3"

MAX_MB_IO = 400          # modbus_master.cpp
MASTER_WORD_BASE = 100   # %IW100 / %QW100
MASTER_BIT_BASE = 800    # %IX100.0 -> Modbus bit address 800

INPUT_WORDS = 49         # FC4 offsets 0..48 (status, self-hold, diag, totalizers)
DISCRETE_BITS = 16       # FC2 offsets 0..15
COIL_BITS = 8            # FC15 offsets 0..7 (no generator breaker coils on v3)
POLLING_PERIOD_MS = 100
TIMEOUT_MS = 1000


def device_index(device: str) -> int:
    return DEVICE_ORDER.index(device)


# -- packed address arithmetic ---------------------------------------------
def input_word(device: str, offset: int) -> int:
    return MASTER_WORD_BASE + INPUT_WORDS * device_index(device) + offset


def holding_word(device: str, offset: int) -> int:
    return (MASTER_WORD_BASE + COMMAND_HOLDING_LENGTH * device_index(device)
            + offset - COMMAND_HOLDING_START)


def discrete_bit(device: str, offset: int) -> int:
    return DISCRETE_BITS * device_index(device) + offset


def coil_bit(device: str, offset: int) -> int:
    return COIL_BITS * device_index(device) + offset


def bit_location(area: str, packed_bit: int) -> str:
    index = MASTER_WORD_BASE + packed_bit // 8
    return f"%{area}{index}.{packed_bit % 8}"


def check_budget() -> None:
    used_words = INPUT_WORDS * len(DEVICE_ORDER)
    if used_words > MAX_MB_IO:
        raise ValueError(f"input image {used_words} words exceeds MAX_MB_IO {MAX_MB_IO}")
    for count in (DISCRETE_BITS, COIL_BITS, COMMAND_HOLDING_LENGTH):
        if count * len(DEVICE_ORDER) > MAX_MB_IO:
            raise ValueError("packed master image exceeds MAX_MB_IO")


# -- artifacts --------------------------------------------------------------
def make_mbconfig(host_mode: str) -> str:
    lines = [
        "# Generated by tools/generate_openplc_v3_gateway.py",
        "# Drop into the OpenPLC v3 webserver directory, or reproduce it in",
        "# Settings -> Slave Devices using slave-devices.csv.  The device ORDER",
        "# is what fixes every %IW/%QW address - do not reorder.",
        "",
        f'Num_Devices = "{len(DEVICE_ORDER)}"',
        f'Polling_Period = "{POLLING_PERIOD_MS}"',
        f'Timeout = "{TIMEOUT_MS}"',
        "",
    ]
    for index, device in enumerate(DEVICE_ORDER):
        host = CONTAINER_HOSTS[device] if host_mode == "container" else "127.0.0.1"
        port = 502 if host_mode == "container" else HOST_PORTS[device]
        lines.extend(
            [
                f"# {index}: {device}",
                f'device{index}.name = "{device}"',
                f'device{index}.slave_id = "1"',
                f'device{index}.protocol = "TCP"',
                f'device{index}.address = "{host}"',
                f'device{index}.IP_Port = "{port}"',
                f'device{index}.Discrete_Inputs_Start = "0"',
                f'device{index}.Discrete_Inputs_Size = "{DISCRETE_BITS}"',
                f'device{index}.Coils_Start = "0"',
                f'device{index}.Coils_Size = "{COIL_BITS}"',
                f'device{index}.Input_Registers_Start = "0"',
                f'device{index}.Input_Registers_Size = "{INPUT_WORDS}"',
                f'device{index}.Holding_Registers_Read_Start = "0"',
                f'device{index}.Holding_Registers_Read_Size = "0"',
                f'device{index}.Holding_Registers_Start = "{COMMAND_HOLDING_START}"',
                f'device{index}.Holding_Registers_Size = "{COMMAND_HOLDING_LENGTH}"',
                "",
            ]
        )
    return "\n".join(lines)


def make_slave_devices_csv(host_mode: str) -> str:
    fields = ("order", "device", "host", "port", "slave_id",
              "discrete_inputs_start", "discrete_inputs_size",
              "coils_start", "coils_size",
              "input_registers_start", "input_registers_size",
              "holding_read_start", "holding_read_size",
              "holding_write_start", "holding_write_size")
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for index, device in enumerate(DEVICE_ORDER):
        writer.writerow({
            "order": index,
            "device": device,
            "host": CONTAINER_HOSTS[device] if host_mode == "container" else "127.0.0.1",
            "port": 502 if host_mode == "container" else HOST_PORTS[device],
            "slave_id": 1,
            "discrete_inputs_start": 0,
            "discrete_inputs_size": DISCRETE_BITS,
            "coils_start": 0,
            "coils_size": COIL_BITS,
            "input_registers_start": 0,
            "input_registers_size": INPUT_WORDS,
            "holding_read_start": 0,
            "holding_read_size": 0,
            "holding_write_start": COMMAND_HOLDING_START,
            "holding_write_size": COMMAND_HOLDING_LENGTH,
        })
    return stream.getvalue()


def mapped_rows(rows: Sequence[Register]) -> list[tuple[Register, str, str, int]]:
    """(row, iec location, northbound table, northbound address) for mapped points."""
    mapped: list[tuple[Register, str, str, int]] = []
    for row in rows:
        if row.table == "INPUT" and row.offset < INPUT_WORDS:
            word = input_word(row.device, row.offset)
            mapped.append((row, f"%IW{word}", "INPUT", word))
        elif row.table == "DISCRETE":
            bit = discrete_bit(row.device, row.offset)
            mapped.append((row, bit_location("IX", bit), "DISCRETE", MASTER_BIT_BASE + bit))
        elif row.table == "COIL" and row.offset < COIL_BITS:
            bit = coil_bit(row.device, row.offset)
            mapped.append((row, bit_location("QX", bit), "COIL", MASTER_BIT_BASE + bit))
        elif (row.table == "HOLDING"
              and COMMAND_HOLDING_START <= row.offset
              < COMMAND_HOLDING_START + COMMAND_HOLDING_LENGTH):
            word = holding_word(row.device, row.offset)
            mapped.append((row, f"%QW{word}", "HOLDING", word))
    return mapped


def make_northbound_csv(rows: Sequence[Register]) -> str:
    fields = ("device", "source_table", "name", "doc_address", "remote_pdu_offset",
              "local_iec", "northbound_table", "northbound_pdu_offset", "dtype",
              "unit", "scale", "writable", "pulse", "plc_forwards", "description")
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for row, location, table, address in mapped_rows(rows):
        writer.writerow({
            "device": row.device,
            "source_table": row.table,
            "name": row.name,
            "doc_address": row.doc_address,
            "remote_pdu_offset": row.offset,
            "local_iec": location,
            "northbound_table": table,
            "northbound_pdu_offset": address,
            "dtype": row.dtype,
            "unit": row.unit,
            "scale": format(row.scale, "g"),
            "writable": "yes" if row.writable else "no",
            "pulse": "yes" if row.pulse else "no",
            "plc_forwards": "yes" if row.table in ("COIL", "HOLDING") else "no",
            "description": row.description,
        })
    return stream.getvalue()


def _pulse_state(device: str, name: str, suffix: str) -> str:
    return f"i_{slug(device)}_{slug(name)}_{suffix}"


def make_program(rows: Sequence[Register]) -> str:
    index = contract_index(rows)
    points = mapped_rows(rows)
    pulse_rows = [row for row, *_ in points if row.table == "COIL" and row.pulse]
    trip_sources = ("turbine", "boiler", "condenser", "feedwater_pump",
                    "condensate_pump", "steam_valve")

    lines = [
        "(* Generated by tools/generate_openplc_v3_gateway.py.",
        "   OpenPLC Runtime v3 gateway for the self-holding thermal plant.",
        "",
        "   The devices start themselves and run their own regulators.  This",
        "   program only exchanges data and evaluates logic; it never computes a",
        "   control value.  The only holding registers written are",
        "   COMMAND_SEQUENCE, WATCHDOG_COUNTER and RESET_KEY.",
        "",
        "   Addresses come from the OpenPLC v3 Modbus master image: slave devices",
        "   must be configured in the order listed in slave-devices.csv. *)",
        "PROGRAM main",
        "  VAR",
        "    i_outputs_initialized : BOOL := FALSE;",
        "    i_watchdog_scan_count : UINT := 0;",
        "    i_watchdog_tick : BOOL := FALSE;",
        "    i_plant_comm_lost : BOOL := FALSE;",
        "    i_overspeed : BOOL := FALSE;",
        "    i_overspeed_prev : BOOL := FALSE;",
    ]
    for device in DEVICE_ORDER:
        lines.extend([
            f"    i_{device}_last_echo : UINT := 0;",
            f"    i_{device}_echo_stale_ticks : UINT := 0;",
            f"    i_{device}_comm_lost : BOOL := FALSE;",
        ])
    for row in pulse_rows:
        lines.extend([
            f"    {_pulse_state(row.device, row.name, 'active')} : BOOL := FALSE;",
            f"    {_pulse_state(row.device, row.name, 'scans')} : UINT := 0;",
        ])
    for device in trip_sources:
        lines.append(f"    i_{device}_trip_prev : BOOL := FALSE;")
    lines.append("")

    seen: set[str] = set()
    for row, location, _, _ in points:
        table = {"INPUT": "input", "DISCRETE": "discrete",
                 "COIL": "coil", "HOLDING": "holding"}[row.table]
        name = alias(row.device, table, row.name)
        if name in seen:
            raise ValueError(f"duplicate alias {name}")
        seen.add(name)
        iec_type = "BOOL" if location.startswith(("%IX", "%QX")) else "UINT"
        initial = "FALSE" if iec_type == "BOOL" else "0"
        lines.append(f"    {name} AT {location} : {iec_type} := {initial};")
    lines.extend(["  END_VAR", ""])

    # first scan: only the command area
    lines.append("  (* First scan: arm the watchdogs.  Nothing else is ever written. *)")
    lines.append("  IF NOT i_outputs_initialized THEN")
    for device in DEVICE_ORDER:
        lines.append(f"    {alias(device, 'holding', 'WATCHDOG_COUNTER')} := 1;")
        lines.append(f"    {alias(device, 'holding', 'COMMAND_SEQUENCE')} := 0;")
        lines.append(f"    {alias(device, 'holding', 'RESET_KEY')} := 0;")
    lines.extend(["    i_outputs_initialized := TRUE;", "  END_IF;", ""])

    # watchdog
    lines.extend([
        f"  (* {WATCHDOG_SCANS * TASK_INTERVAL_MS} ms non-zero watchdog for every device. *)",
        "  i_watchdog_tick := FALSE;",
        "  i_watchdog_scan_count := i_watchdog_scan_count + 1;",
        f"  IF i_watchdog_scan_count >= {WATCHDOG_SCANS} THEN",
        "    i_watchdog_scan_count := 0;",
        "    i_watchdog_tick := TRUE;",
    ])
    for device in DEVICE_ORDER:
        wd = alias(device, "holding", "WATCHDOG_COUNTER")
        lines.extend([
            f"    IF {wd} >= 65535 THEN",
            f"      {wd} := 1;",
            "    ELSE",
            f"      {wd} := {wd} + 1;",
            "    END_IF;",
        ])
    lines.extend(["  END_IF;", ""])

    # echo supervision
    lines.extend([
        "  (* Echo lags the counter because FC4 polls every 250 ms; an unchanged",
        f"     mismatch for {ECHO_STALE_TICKS} ticks is a communication failure. *)",
        "  IF i_watchdog_tick THEN",
    ])
    for device in DEVICE_ORDER:
        echo = alias(device, "input", "WATCHDOG_ECHO")
        wd = alias(device, "holding", "WATCHDOG_COUNTER")
        lines.extend([
            f"    IF ({echo} = {wd}) OR ({echo} <> i_{device}_last_echo) THEN",
            f"      i_{device}_last_echo := {echo};",
            f"      i_{device}_echo_stale_ticks := 0;",
            "    ELSE",
            f"      IF i_{device}_echo_stale_ticks < 65535 THEN",
            f"        i_{device}_echo_stale_ticks := i_{device}_echo_stale_ticks + 1;",
            "      END_IF;",
            "    END_IF;",
            f"    i_{device}_comm_lost := i_{device}_echo_stale_ticks >= {ECHO_STALE_TICKS};",
        ])
    lines.extend([
        "  END_IF;",
        "",
        "  (* Communication loss is a status, not an action: the devices keep",
        "     running on their own regulators. *)",
        "  i_plant_comm_lost := "
        + " OR ".join(f"i_{device}_comm_lost" for device in DEVICE_ORDER) + ";",
        "",
        f"  (* Pulse commands are stretched to about {PULSE_SCANS * TASK_INTERVAL_MS} ms",
        "     then cleared.  EMERGENCY_STOP and FORCE_SAFE are maintained. *)",
    ])
    for row in pulse_rows:
        command = alias(row.device, "coil", row.name)
        active = _pulse_state(row.device, row.name, "active")
        scans = _pulse_state(row.device, row.name, "scans")
        sequence = alias(row.device, "holding", "COMMAND_SEQUENCE")
        reset_key = alias(row.device, "holding", "RESET_KEY")
        lines.extend([
            f"  IF {command} AND NOT {active} THEN",
            f"    {active} := TRUE;",
            f"    {scans} := 0;",
        ])
        if row.name == "RESET_TRIP":
            lines.extend([
                f"    IF {sequence} >= 65535 THEN",
                f"      {sequence} := 1;",
                "    ELSE",
                f"      {sequence} := {sequence} + 1;",
                "    END_IF;",
                f"    {reset_key} := {RESET_KEY};",
            ])
        lines.extend([
            "  END_IF;",
            f"  IF {active} THEN",
            f"    {scans} := {scans} + 1;",
            f"    IF {scans} >= {PULSE_SCANS} THEN",
            f"      {command} := FALSE;",
            f"      {active} := FALSE;",
            f"      {scans} := 0;",
        ])
        if row.name == "RESET_TRIP":
            lines.append(f"      {reset_key} := 0;")
        lines.extend(["    END_IF;", "  END_IF;"])
    lines.append("")

    # trip matrix (commands only; v3 has no generator breaker coils)
    trip_actions = {
        "turbine": [f"{alias('steam_valve', 'coil', 'STOP')} := TRUE;"],
        "boiler": [f"{alias('steam_valve', 'coil', 'STOP')} := TRUE;"],
        "condenser": [],
        "feedwater_pump": [f"{alias('boiler', 'coil', 'STOP')} := TRUE;"],
        "condensate_pump": [],
        "steam_valve": [f"{alias('boiler', 'coil', 'STOP')} := TRUE;"],
    }
    lines.append("  (* Rising-edge plant trip matrix, commands only. *)")
    for source, actions in trip_actions.items():
        tripped = alias(source, "discrete", "TRIPPED")
        if index.get((source, "DISCRETE", 4)) is None:
            raise ValueError(f"{source}: TRIPPED discrete missing from the contract")
        lines.append(f"  IF {tripped} AND NOT i_{source}_trip_prev THEN")
        lines.extend(f"    {action}" for action in actions)
        if not actions:
            lines.append("    (* device-level interlocks are sufficient *)")
        lines.extend(["  END_IF;", f"  i_{source}_trip_prev := {tripped};"])

    lines.extend([
        "",
        "  (* Overspeed independently stops the main steam valve. *)",
        f"  i_overspeed := ({alias('turbine', 'input', 'SPEED_RPM')} > {OVERSPEED_RAW_RPM})"
        f" OR {alias('turbine', 'discrete', 'TRIPPED')};",
        "  IF i_overspeed AND NOT i_overspeed_prev THEN",
        f"    {alias('steam_valve', 'coil', 'STOP')} := TRUE;",
        "  END_IF;",
        "  i_overspeed_prev := i_overspeed;",
        "END_PROGRAM",
        "",
        "CONFIGURATION Config0",
        "",
        "  RESOURCE Res0 ON PLC",
        f"    TASK task0(INTERVAL := T#{TASK_INTERVAL_MS}ms,PRIORITY := 0);",
        "    PROGRAM instance0 WITH task0 : main;",
        "  END_RESOURCE",
        "END_CONFIGURATION",
        "",
    ])
    return "\n".join(lines)


def make_readme(host_mode: str) -> str:
    rows = "\n".join(
        f"| {index} | `{device}` | `{CONTAINER_HOSTS[device]}:502` | "
        f"`127.0.0.1:{HOST_PORTS[device]}` | %IW{input_word(device, 0)}"
        f"..%IW{input_word(device, INPUT_WORDS - 1)} | "
        f"{bit_location('IX', discrete_bit(device, 0))} | "
        f"{bit_location('QX', coil_bit(device, 0))} | "
        f"%QW{holding_word(device, COMMAND_HOLDING_START)} |"
        for index, device in enumerate(DEVICE_ORDER)
    )
    return f"""# Thermal Plant OpenPLC v3 gateway

OpenPLC Runtime v3 version of the gateway.  Same role as the v4 project: the
八 devices are self-holding, so the PLC only exchanges data and evaluates
logic - watchdog, echo supervision, pulse stretching, trip matrix, overspeed.
It never writes a setpoint or a manual output.

Generated southbound mode: **{host_mode}**.

```sh
python3 -m tools.generate_openplc_v3_gateway
python3 -m tools.generate_openplc_v3_gateway --check
```

## Why v3 needs its own map

v3 does not let the editor choose IEC addresses.  Its Modbus master packs every
configured slave device into fixed buffers (`modbus_master.cpp`):

```text
%IX100.0+   discrete inputs      %QX100.0+   coils
%IW100+     input registers      %QW100+     holding registers (write)
```

Each buffer holds at most 400 entries, so with eight devices this project polls
**49 input words** per device (392 of 400) and therefore has:

* no FC3 holding readback (v4 has it at `%IW512+`) - SCADA cannot read back
  setpoints through v3;
* one 8-bit coil block per device, so the generator breaker coils (offsets
  9/10, v4 only) are not exposed.  The generator synchronises itself, and the
  trip matrix uses `STOP`, so no plant function is lost.

The device **order below is what fixes every address** - do not reorder it.

| # | Device | Container mode | Host mode | Input regs | Discretes | Coils | Commands |
| ---: | --- | --- | --- | --- | --- | --- | --- |
{rows}

## Setup

1. Start the simulator with the v3 profile:

   ```sh
   COMPOSE_PROFILES=openplc-v3 docker compose up --build
   ```

2. Open the v3 web interface on <http://127.0.0.1:15083> (default login
   `openplc` / `openplc`).

3. Programs -> Upload `thermal-plant-v3.st`, then compile it.

4. Slave Devices -> add the eight devices exactly in the order and with the
   ranges in `slave-devices.csv`.  Alternatively copy `mbconfig.cfg` into the
   runtime's webserver directory.

5. Settings -> enable **Modbus** (the northbound server on port 502, published
   as `127.0.0.1:15020`), then Start PLC.

`northbound-map.csv` is the SCADA/HMI address list for this layout.  Note that
the ScadaBR import shipped in `integrations/scadabr/` targets the **v4** flat
layout; for v3 use these addresses instead.

## What the operator does

`START` clears the operator-stop lock and lets the device hold itself again;
`STOP` latches it stopped.  Everything else - setpoints, ramps, sequencing -
is the device's own business.
"""


def build_files(rows: Sequence[Register], host_mode: str) -> dict[Path, str]:
    check_budget()
    return {
        Path("thermal-plant-v3.st"): make_program(rows),
        Path("mbconfig.cfg"): make_mbconfig(host_mode),
        Path("slave-devices.csv"): make_slave_devices_csv(host_mode),
        Path("northbound-map.csv"): make_northbound_csv(rows),
        Path("README.md"): make_readme(host_mode),
    }


def write_files(output: Path, files: dict[Path, str]) -> tuple[int, int]:
    written = unchanged = 0
    for relative, content in sorted(files.items()):
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_text(encoding="utf-8") == content:
            unchanged += 1
            continue
        path.write_text(content, encoding="utf-8")
        written += 1
    return written, unchanged


def check_files(output: Path, files: dict[Path, str]) -> list[str]:
    problems = []
    for relative, content in sorted(files.items()):
        path = output / relative
        if not path.exists():
            problems.append(f"missing {relative}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"stale {relative}")
    return problems


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the OpenPLC v3 gateway")
    parser.add_argument("--map", type=Path, default=DEFAULT_MAP)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--host-mode", choices=("container", "host"), default="container")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        rows = load_contract(args.map.resolve())
        files = build_files(rows, args.host_mode)
    except ValueError as error:
        print(f"[FAIL] {error}", file=sys.stderr)
        return 1
    if args.check:
        problems = check_files(args.output.resolve(), files)
        for problem in problems:
            print(f"[FAIL] {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"[PASS] OpenPLC v3 gateway up to date ({len(files)} files)")
        return 0
    written, unchanged = write_files(args.output.resolve(), files)
    print(f"[PASS] OpenPLC v3 gateway generated ({written} written, {unchanged} unchanged)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
